name: medsam-final-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - pydicom
  - pillow
  - nibabel
  - requests
  - fastapi
  - uvicorn
  - python-multipart
  - celery
  - redis
  - pip:
    - gradio==4.29.0